spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlinestore?serverTimezone=America/Chicago&useSSL=false
    username: root
    password: vEGfTA8triZC.TbZ32P-
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  h2:
    console.enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: false